// lib/core/constants/municipios_chiapas.dart

const List<String> municipiosChiapas = [
  "Acacoyagua",
  "Acala",
  "Acapetahua",
  "Aldama",
  "Altamirano",
  "Amatán",
  "Amatenango de la Frontera",
  "Amatenango del Valle",
  "Angel Albino Corzo",
  "Arriaga",
  "Bejucal de Ocampo",
  "Bella Vista",
  "Benemérito de las Américas",
  "Berriozábal",
  "Bochil",
  "Cacahoatán",
  "Catazajá",
  "Chalchihuitán",
  "Chamula",
  "Chanal",
  "Chapultenango",
  "Chenalhó",
  "Chiapa de Corzo",
  "Chiapilla",
  "Chicoasén",
  "Chicomuselo",
  "Chilón",
  "Cintalapa",
  "Coapilla",
  "Comitán de Domínguez",
  "Copainalá",
  "El Bosque",
  "El Parral",
  "El Porvenir",
  "Escuintla",
  "Francisco León",
  "Frontera Comalapa",
  "Frontera Hidalgo",
  "Huehuetán",
  "Huitiupán",
  "Huixtán",
  "Huixtla",
  "Ixhuatán",
  "Ixtacomitán",
  "Ixtapa",
  "Ixtapangajoya",
  "Jiquipilas",
  "Jitotol",
  "Juárez",
  "La Concordia",
  "La Grandeza",
  "La Independencia",
  "La Libertad",
  "La Trinitaria",
  "Larráinzar",
  "Las Margaritas",
  "Las Rosas",
  "Mapastepec",
  "Maravilla Tenejapa",
  "Marqués de Comillas",
  "Mazapa de Madero",
  "Mazatán",
  "Metapa",
  "Mezcalapa",
  "Mitontic",
  "Montecristo de Guerrero",
  "Motozintla",
  "Nicolás Ruíz",
  "Ocosingo",
  "Ocotepec",
  "Ocozocoautla de Espinosa",
  "Ostuacán",
  "Osumacinta",
  "Oxchuc",
  "Palenque",
  "Pantelhó",
  "Pantepec",
  "Pichucalco",
  "Pijijiapan",
  "Pueblo Nuevo Solistahuacán",
  "Rayón",
  "Reforma",
  "Sabanilla",
  "Salto de Agua",
  "San Andrés Duraznal",
  "San Cristóbal de Las Casas",
  "San Fernando",
  "San Juan Cancuc",
  "San Lucas",
  "Santiago el Pinar",
  "Siltepec",
  "Simojovel",
  "Sitalá",
  "Socoltenango",
  "Solosuchiapa",
  "Soyaló",
  "Suchiapa",
  "Suchiate",
  "Sunuapa",
  "Tapachula",
  "Tapalapa",
  "Tapilula",
  "Tecpatán",
  "Tenejapa",
  "Teopisca",
  "Tila",
  "Tonalá",
  "Totolapa",
  "Tumbalá",
  "Tuxtla Chico",
  "Tuxtla Gutiérrez",
  "Tuzantán",
  "Tzimol",
  "Unión Juárez",
  "Venustiano Carranza",
  "Villa Comaltitlán",
  "Villa Corzo",
  "Villaflores",
  "Yajalón",
  "Zinacantán",
];
